// Workaround for https://github.com/rust-lang/rust-bindgen/issues/753#issuecomment-308901773

#include <nvEncodeAPI.h>

const uint32_t _NV_ENC_OPEN_ENCODE_SESSION_EX_PARAMS_VER = NV_ENC_OPEN_ENCODE_SESSION_EX_PARAMS_VER;
#undef NV_ENC_OPEN_ENCODE_SESSION_EX_PARAMS_VER
const uint32_t NV_ENC_OPEN_ENCODE_SESSION_EX_PARAMS_VER = _NV_ENC_OPEN_ENCODE_SESSION_EX_PARAMS_VER;

const uint32_t _NV_ENC_INITIALIZE_PARAMS_VER = NV_ENC_INITIALIZE_PARAMS_VER;
#undef NV_ENC_INITIALIZE_PARAMS_VER
const uint32_t NV_ENC_INITIALIZE_PARAMS_VER = _NV_ENC_INITIALIZE_PARAMS_VER;

const uint32_t _NV_ENC_RECONFIGURE_PARAMS_VER = NV_ENC_RECONFIGURE_PARAMS_VER;
#undef NV_ENC_RECONFIGURE_PARAMS_VER
const uint32_t NV_ENC_RECONFIGURE_PARAMS_VER = _NV_ENC_RECONFIGURE_PARAMS_VER;

const uint32_t _NV_ENC_PRESET_CONFIG_VER = NV_ENC_PRESET_CONFIG_VER;
#undef NV_ENC_PRESET_CONFIG_VER
const uint32_t NV_ENC_PRESET_CONFIG_VER = _NV_ENC_PRESET_CONFIG_VER;

const uint32_t _NV_ENC_CONFIG_VER = NV_ENC_CONFIG_VER;
#undef NV_ENC_CONFIG_VER
const uint32_t NV_ENC_CONFIG_VER = _NV_ENC_CONFIG_VER;

const uint32_t _NV_ENCODE_API_FUNCTION_LIST_VER = NV_ENCODE_API_FUNCTION_LIST_VER;
#undef NV_ENCODE_API_FUNCTION_LIST_VER
const uint32_t NV_ENCODE_API_FUNCTION_LIST_VER = _NV_ENCODE_API_FUNCTION_LIST_VER;

const uint32_t _NV_ENC_PIC_PARAMS_VER = NV_ENC_PIC_PARAMS_VER;
#undef NV_ENC_PIC_PARAMS_VER
const uint32_t NV_ENC_PIC_PARAMS_VER = _NV_ENC_PIC_PARAMS_VER;


const uint32_t _NV_ENC_CREATE_INPUT_BUFFER_VER = NV_ENC_CREATE_INPUT_BUFFER_VER;
#undef NV_ENC_CREATE_INPUT_BUFFER_VER
const uint32_t NV_ENC_CREATE_INPUT_BUFFER_VER = _NV_ENC_CREATE_INPUT_BUFFER_VER;

const uint32_t _NV_ENC_LOCK_INPUT_BUFFER_VER = NV_ENC_LOCK_INPUT_BUFFER_VER;
#undef NV_ENC_LOCK_INPUT_BUFFER_VER
const uint32_t NV_ENC_LOCK_INPUT_BUFFER_VER = _NV_ENC_LOCK_INPUT_BUFFER_VER;



const uint32_t _NV_ENC_CREATE_BITSTREAM_BUFFER_VER = NV_ENC_CREATE_BITSTREAM_BUFFER_VER;
#undef NV_ENC_CREATE_BITSTREAM_BUFFER_VER
const uint32_t NV_ENC_CREATE_BITSTREAM_BUFFER_VER = _NV_ENC_CREATE_BITSTREAM_BUFFER_VER;

const uint32_t _NV_ENC_LOCK_BITSTREAM_VER = NV_ENC_LOCK_BITSTREAM_VER;
#undef NV_ENC_LOCK_BITSTREAM_VER
const uint32_t NV_ENC_LOCK_BITSTREAM_VER = _NV_ENC_LOCK_BITSTREAM_VER;
