// Workaround for https://github.com/rust-lang/rust-bindgen/issues/753#issuecomment-308901773

#include <nvEncodeAPI.h>

const uint32_t _NV_ENC_OPEN_ENCODE_SESSION_EX_PARAMS_VER = NV_ENC_OPEN_ENCODE_SESSION_EX_PARAMS_VER;
#undef NV_ENC_OPEN_ENCODE_SESSION_EX_PARAMS_VER
const uint32_t NV_ENC_OPEN_ENCODE_SESSION_EX_PARAMS_VER = _NV_ENC_OPEN_ENCODE_SESSION_EX_PARAMS_VER;

const uint32_t _NV_ENCODE_API_FUNCTION_LIST_VER = NV_ENCODE_API_FUNCTION_LIST_VER;
#undef NV_ENCODE_API_FUNCTION_LIST_VER
const uint32_t NV_ENCODE_API_FUNCTION_LIST_VER = _NV_ENCODE_API_FUNCTION_LIST_VER;
